/**
 * Where every legacy URL goes.
 *
 * The WordPress site at multimulk.com is being replaced by this one, and its
 * URLs carry whatever ranking the business has. They are answered with a
 * permanent redirect rather than left to 404.
 *
 * Two decisions worth knowing about:
 *
 *  - Everything lands on `/en/…`. The legacy site was English-only, so
 *    consolidating there keeps each redirect a single hop and avoids a
 *    permanent redirect that varies on `Accept-Language` — which is what
 *    sending these through the locale proxy would produce.
 *  - Next evaluates `redirects()` from `next.config.ts` *before* `proxy.ts`,
 *    so these are resolved before locale prefixing ever runs. That ordering is
 *    what makes the single hop possible.
 *
 * Generated by `scripts/migrate-legacy.mjs`; the hand-written section above
 * the generated lists is maintained here.
 */

export type LegacyRedirect = { from: string; to: string };

/**
 * The pillar and country pages.
 *
 * The legacy tree is country-first (`/turkey/turkey-citizenship-by-investment/`)
 * and the new one is pillar-first, so these are mapped by hand — there is no
 * rule that derives one from the other.
 */
const pages: LegacyRedirect[] = [
  { from: "/turkey/turkey-citizenship-by-investment", to: "/citizenship-by-investment/turkiye" },
  {
    from: "/turkey/turkey-citizenship-by-investment/bank-deposit-route",
    to: "/citizenship-by-investment/turkiye/bank-deposit",
  },
  { from: "/turkey/turkey-real-estate", to: "/real-estate/turkiye" },
  { from: "/turkey/turkey-real-estate/ready-properties", to: "/search-property?location=T%C3%BCrkiye" },
  { from: "/turkey/turkey-real-estate/off-plan-properties", to: "/search-property?location=T%C3%BCrkiye" },
  { from: "/turkey", to: "/countries/turkiye" },

  { from: "/uae/golden-visa", to: "/golden-visa/uae" },
  { from: "/uae/real-estate-investment", to: "/real-estate/uae" },
  { from: "/uae/real-estate-investment/ready-properties", to: "/search-property?location=UAE" },
  { from: "/uae/real-estate-investment/off-plan-properties", to: "/search-property?location=UAE" },
  { from: "/uae", to: "/countries/uae" },

  { from: "/eu/residency-by-investment", to: "/golden-visa" },
  { from: "/eu/portugal", to: "/golden-visa/portugal" },
  { from: "/eu/greece", to: "/golden-visa/greece" },
  { from: "/eu/malta", to: "/golden-visa/malta" },
  { from: "/eu/spain", to: "/golden-visa/spain" },
  { from: "/eu/cyprus", to: "/golden-visa/cyprus" },
  { from: "/eu", to: "/golden-visa" },

  { from: "/caribbean/citizenship-by-investment", to: "/citizenship-by-investment/caribbean" },
  { from: "/caribbean/grenada", to: "/citizenship-by-investment/grenada" },
  { from: "/caribbean/dominica", to: "/citizenship-by-investment/dominica" },
  { from: "/caribbean/st-kitts-and-nevis", to: "/citizenship-by-investment/st-kitts-and-nevis" },
  { from: "/caribbean/st-lucia", to: "/citizenship-by-investment/st-lucia" },
  { from: "/caribbean/antigua-and-barbuda", to: "/citizenship-by-investment/antigua-and-barbuda" },
  { from: "/caribbean", to: "/citizenship-by-investment/caribbean" },

  { from: "/about-us", to: "/about" },
  { from: "/about-us-2", to: "/about" },
  { from: "/services", to: "/about" },
  { from: "/contact", to: "/contact-us" },
  { from: "/submit-interest", to: "/contact-us" },
  { from: "/submit-your-interest", to: "/contact-us" },
  { from: "/privacy-policy", to: "/legal/privacy-policy" },
  { from: "/blog", to: "/knowledge" },
  { from: "/interstellar-tower", to: "/properties/the-interstellar-tower" },

  // This site's own pre-restructure URLs. They were only ever reachable in
  // development, but they are cheap to answer and expensive to have missed.
  { from: "/citizenship/turkiye", to: "/citizenship-by-investment/turkiye" },
  { from: "/citizenship/caribbean", to: "/citizenship-by-investment/caribbean" },
  { from: "/media-centre", to: "/knowledge" },

  // Two paths the legacy sitemap still lists that its own REST API does not
  // return. One already 404s there; the other 301s to an article we do carry,
  // so it is pointed straight at the destination rather than chained.
  {
    from: "/caribbean-citizenship-by-investment-a-smart-move-for-global-investors",
    to: "/knowledge/caribbean-citizenship-by-investment",
  },
];

/**
 * Legacy blog categories. The new Knowledge Centre filters on a query
 * parameter rather than owning a path per category, so these collapse onto it.
 */
const categories: LegacyRedirect[] = [
  // Two sets, deliberately. The legacy sitemap and the legacy REST API do not
  // list the same category slugs — the sitemap still advertises paths the API
  // no longer knows about — and both are indexed. Redirecting only the ones
  // the API reports would leave the sitemap's own URLs dead.
  { from: "/category/blog", to: "/knowledge" },
  { from: "/category/cbi", to: "/knowledge?topic=citizenship" },
  { from: "/category/caribbean-citizenship", to: "/knowledge?topic=citizenship" },
  { from: "/category/citizenship-by-investment", to: "/knowledge?topic=citizenship" },
  { from: "/category/eu-residency-programs", to: "/knowledge?topic=residency" },
  { from: "/category/global-mobility-residency", to: "/knowledge?topic=residency" },
  { from: "/category/uae-real-estate-golden-visa", to: "/knowledge?topic=residency" },
  { from: "/category/realestate", to: "/knowledge?topic=real-estate" },
  { from: "/category/investment-market-insights", to: "/knowledge?topic=real-estate" },
  { from: "/category/news", to: "/knowledge?topic=news" },
  { from: "/category/company-updates-announcements", to: "/knowledge?topic=news" },
];

/**
 * Paths that should never have been public: theme demos and page-builder
 * scratch pages. They are answered 410 rather than redirected, because there
 * is nothing they correspond to and a redirect would imply otherwise.
 */
export const legacyGone: string[] = [
  // Already 404 on the legacy site, but still advertised in its sitemap.
  "/why-some-turkish-citizenship-applications-get-rejected-and-how-to-ensure-yours-isnt",

  "/houzez-studio/search-results",
  "/houzez-studio/listing-me",
  "/houzez-studio/block-v2",
  "/houzez-studio/real-estate-block",
  "/houzez-studio/test",
  "/elementor-7375",
  "/offplanprojects/off-plan-projects",
  "/property-type/apartment",
  "/ready-properties/ready-properties",
  "/ready-properties/offplan",
  "/uae-off-plan-properties/uae-off-plan-projects",
  "/uae-off-plan-properties/uae-off-plan-properties",
  "/uae-ready-properties/uae-ready-properties",
];

/** Article slugs, which sat at the site root and now live under /knowledge. */
const articleSlugs: string[] = [
  "27-million-tourists-in-the-first-half-of-2026-what-turkiyes-tourism-boom-means-for-real-estate-investment",
  "after-citizenship-how-to-open-a-turkish-bank-account-and-move-money-internationally-without-flags",
  "best-caribbean-countries-offering-citizenship-through-real-estate-investment",
  "best-cities-in-turkey-to-invest-for-citizenship",
  "best-school-districts-in-istanbul-for-hnwi-families-where-citizenship-investors-actually-settle-in-2026",
  "blog-benefits-turkish-passport-holders-e2-eb5-us-visas",
  "blog-why-choose-multimulk-e2-eb5-us-visa",
  "bodrum-marmaris-fethiye-antalya-real-estate-guide",
  "can-you-sell-property-after-3-years-turkey-cbi-exit-strategy",
  "caribbean-citizenship-by-investment",
  "cbi-due-diligence-in-turkey-what-background-checks-applicants-face-and-what-disqualifies-you-in-2026",
  "citizenship-by-investment-a-gateway-to-global-freedom-and-secure-real-estate",
  "dual-tax-resident-by-design-how-hnwis-use-turkish-citizenship-to-legally-reduce-their-tax-burden",
  "e-2-visa-usa-through-turkish-citizenship-the-complete-guide",
  "end-to-end-turkish-citizenship-advisory",
  "eu-residency-programs-your-pathway-to-european-living-and-investment",
  "fastest-cities-in-turkey-to-get-citizenship-approved-in-2026",
  "five-red-flags-that-mean-your-turkey-cbi-agent-is-cutting-corners-and-how-to-spot-them",
  "global-mobility-residency-building-a-borderless-lifestyle-through-investment",
  "global-real-estate-investment-trends-every-investor-should-know",
  "healthcare-in-turkey-for-foreigners-public-vs-private",
  "hidden-costs-of-turkish-citizenship-by-investment-in-2026",
  "how-citizenship-by-investment-programs-work-a-step-by-step-guide",
  "how-citizenship-by-investment-programs-work-a-step-by-step-guide-2",
  "how-global-residency-programs-help-investors-secure-international-freedom",
  "how-mecca-alliance-impacts-investors",
  "how-smart-investors-use-market-insights-to-maximize-international-investments",
  "how-to-choose-between-residency-vs-second-citizenship",
  "how-to-qualify-for-the-uae-golden-visa-through-property-investment",
  "https-multimulk-com-blog-choosing-your-advisor-can-save-your-future",
  "https-multimulk-com-blog-deutsche-bank-report-istanbul-property-surge-foreigners-guidehttps-multimulk-com-blog-deutsche-bank-report-istanbul-property-surge-foreigners-guide",
  "https-multimulk-com-blog-how-to-choose-a-turkish-citizenship-advisor-2026https-multimulk-com-blog-how-to-choose-a-turkish-citizenship-advisor-2026",
  "https-multimulk-com-blog-turkiye-to-cancel-687-citizenships-how-to-avoid-fraudulent-companies",
  "https-multimulk-com-blog-where-is-the-real-estate-market-index-in-turkiye-heading",
  "interstellar-tower",
  "is-the-turkey-cbi-program-at-risk-of-closing-what-the-2026-signals-actually-mean",
  "is-turkish-citizenship-worth-it-in-2026-pros-cons",
  "lira-vs-dollar-in-2026-does-currency-risk-affect-your-turkish-citizenship-investment",
  "looking-for-a-second-passport-which-program-is-right-for-you-in-2026",
  "minimum-investment-for-turkey-citizenship-in-2026-the-400000-rule-fully-explained",
  "mount-anvil-chelsea-finery-london-investment-turkey",
  "multimulk-achieves-new-milestone-in-international-real-estate-citizenship-advisory",
  "multimulk-com-blog-foreign-real-estate-investment-turkeyhttps-multimulk-com-blog-foreign-real-estate-investment-turkey",
  "multimulk-expands-its-investment-advisory-services-to-serve-global-clients",
  "new-2026-turkey-biometrics-rule-what-you-need-to-know",
  "no-worldwide-tax-no-inheritance-tax-why-turkeys-tax-system-is-attracting-gulf-family-offices-in-2026",
  "real-estate-vs-bank-deposit-for-turkey-citizenship",
  "rental-yields-in-turkey-vs-dubai-2026",
  "the-400k-question-what-does-turkish-citizenship-actually-cost-all-in-in-2026",
  "the-istanbul-penthouse-play-luxury-real-estate-that-qualifies-for-turkish-citizenship-and-earns-rental-income-2026",
  "top-eu-residency-programs-through-real-estate-investment",
  "turkey-cbi-vs-caribbean-cbi-which-one-is-better-in-2026",
  "turkey-citizenship-by-investment-400000-can-you-split-the-requirement-across-two-properties",
  "turkey-citizenship-by-investment-vs-greece-golden-visa-which-second-residency-program-is-right-for-you-in-2026",
  "turkey-citizenship-for-families-benefits-facts-timeline",
  "turkey-citizenship-for-pakistani-nationals-full-guide-2026",
  "turkey-citizenship-revoked-what-actually-triggers-it-2026",
  "turkey-citizenship-vs-caribbean-citizenship-by-investment",
  "turkey-real-estate-market-forecast-2026",
  "turkey-vs-malta-vs-portugal-citizenship-in-2026-a-side-by-side-for-serious-investors",
  "turkish-citizenship-application-process-2026",
  "turkish-citizenship-by-investment-guide-2026-edition",
  "turkish-citizenship-by-property-investment-2026",
  "turkish-passport-visa-free-list-2026-the-countries-that-matter-most-for-business-travel",
  "turkish-real-estate-purchase-inside-a-holding-company",
  "turkiye-property-tax-construction-values-2027",
  "uae-real-estate-golden-visa-a-powerful-combination-for-global-investors",
  "uae-resident-turkey-citizen-can-you-hold-both",
  "using-turkish-citizenship-to-access-the-us-e-2-investor-visa-the-full-2026-playbook",
  "what-actually-happens-on-turkish-citizenship-approval-day-documents-timeline-and-what-to-expect",
  "why-wealthy-investors-are-quietly-moving-assets-to-turkey-before-the-next-g20-tax-crackdown",
];

/** Development slugs, moving from /projects/<slug> to /properties/<slug>. */
const projectSlugs: string[] = [
  "6656",
  "a-beautiful-mix-used-project-in-atasehir-istanbul",
  "a-boutique-residential-living-space-designed-to-bring-you-closer-to-nature",
  "a-brand-new-ecosystem-in-the-historical-heart-of-the-city",
  "a-comprehensive-residential-and-lifestyle-destination-by-the-sea",
  "a-dedicated-medical-complex-designed-for-modern-healthcare",
  "a-fresh-spring-of-luxury-and-nature-in-a-developing-modern-center",
  "a-fusion-of-historical-heritage-and-cutting-edge-modernity",
  "a-gateway-to-modern-living-in-the-city-center",
  "a-glamorous-life-between-the-marina-and-the-sea",
  "a-harmonious-blend-of-boutique-luxury-and-urban-rhythm",
  "a-high-traffic-commercial-hub-at-the-intersection-of-major-transit-lines",
  "a-legacy-of-elegance-in-the-heart-of-history-besiktas",
  "a-lush-villa-life-in-istanbul",
  "a-luxury-project-with-sea-and-lake-view",
  "a-modern-and-luxury-project-nestled-in-the-beginning-of-kartal-istanbul",
  "a-modern-haven-of-boutique-luxury-in-the-historic-city-center",
  "a-modern-island-of-tranquility-in-the-heart-of-the-city",
  "a-modern-jewel-in-the-heart-of-the-historic-peninsula",
  "a-modern-mixed-use-community-in-the-heart-of-an-academic-and-business-hub",
  "a-modern-mixed-use-development-combining-residences-offices-and-residence",
  "a-modern-mixed-use-landmark-bringing-living-working-and-commerce-together-in-atasehir",
  "a-modern-project-located-in-the-prestigious-gokturk-area-of-istanbul",
  "a-modern-urban-oasis-in-the-heart-of-the-city",
  "a-natural-life-with-every-breathin-in-ist",
  "a-new-benchmark-for-family-comfort-and-modern-neighborhood-life",
  "a-new-ecosystem-in-the-historical-part-of-city-taksim",
  "a-new-era-of-modern-residence-living",
  "a-premier-boutique-community-in-the-heart-of-the-financial-district",
  "a-premier-sea-view-residential-projects-located-in-buyukcekmece",
  "a-premium-residential-sanctuary-and-green-oasis-in-the-city",
  "a-premium-residential-sanctuary-and-green-oasis-in-the-city-2",
  "a-prestigious-life-at-the-heart-of-the-city",
  "a-prestigious-oasis-where-history-meets-modernity",
  "a-prestigious-project-nestled-in-the-heart-of-kadikoy-istanbul",
  "a-prestigious-urban-sanctuary-in-the-heart-of-the-city",
  "a-pretigious-life-with-a-lake-view",
  "a-prime-project-with-sea-views-easy-transport-and-green-living",
  "a-privileged-life-with-princes-islands-views",
  "a-remarkable-new-project-in-the-prime-location-of-erenkoy",
  "a-scenic-blend-of-historical-charm-and-modern-living",
  "a-seamless-intersection-of-business-precision-and-home-comfort",
  "a-serene-boutique-living-experience-in-a-rapidly-developing-hub",
  "a-serene-boutique-sanctuary-inspired-by-nature",
  "a-striking-modern-renaissance-in-the-citys-new-financial-center",
  "a-trusted-legacy-of-family-oriented-living",
  "a-trusted-legacy-of-family-oriented-living-in-a-planned-residential-hub",
  "a-vibrant-green-living-experience-in-the-heart-of-zeytinburnu",
  "add-comfort-and-privileges-to-your-life",
  "amra",
  "an-exclusive-development-nestled-on-istanbuls-asian-side",
  "an-iconic-mixed-use-landmark-in-a-high-value-investment-zone",
  "bayz-102",
  "binghatti-hillviews",
  "breez",
  "canal-heights",
  "comfortable-living-designed-for-everyday-happiness-in-beylikduzu",
  "feel-the-comfort-and-luxury-all-in-one",
  "greenz-by-danube",
  "healthy-living-in-the-heart-of-the-business-world",
  "in-istanbuls-heart-with-japanese-feel",
  "italian-style-house-in-istanbul",
  "knightsbridge-phase-1",
  "le-blanc",
  "life-in-the-heart-of-besiktas",
  "low-rise-high-intelligence-living",
  "luxurious-living-with-a-hotel-inspired-concept-offering-high-quality-residences",
  "luxury-living-in-the-heart-of-history",
  "luxury-villa-residences-with-modern-architectural-design",
  "modern-family-living-and-boutique-luxury-in-a-growing-hub",
  "modern-houses-in-historical-central-district",
  "modern-living-inspired-by-italian-design-in-sariyer-istanbul",
  "novotel-recidences",
  "oasis-residences",
  "pearl-house-4",
  "premium-investment-opportunity-on-basin-ekspres-road",
  "prestigious-project-in-umraniye-with-strategic-location",
  "prime-residential-living-next-to-tem",
  "refined-elegance-and-quiet-luxury-in-the-heart-of-the-finance-district",
  "sakura-gardens",
  "serenz",
  "serenz-by-danube",
  "stamn-one",
  "strategically-located-business-destination-near-metro-and-e-5",
  "the-essence-of-luxury-in-beylikduzu",
  "the-interstellar-tower",
  "the-meriva-collection",
  "the-modern-forest-retreat",
  "the-newest-destination-of-urban-life",
  "the-place-by-prestige-one",
  "the-symphony",
  "vega",
  "where-luxury-meets-convenience-offering-a-harmonious-blend-of-residential-and-commercial",
  "where-nature-becomes-home",
];

/** Every legacy path and where it now goes, locale-free. */
export const legacyRedirects: LegacyRedirect[] = [
  ...pages,
  ...categories,
  ...articleSlugs.map((slug) => ({ from: `/${slug}`, to: `/knowledge/${slug}` })),
  ...projectSlugs.map((slug) => ({ from: `/projects/${slug}`, to: `/properties/${slug}` })),
];
