/**
 * Property units shown on /search-property.
 *
 * NOTE: placeholder inventory — project names, unit specs, prices and
 * photography are stand-ins and must be replaced with Multi Mulk's real
 * Türkiye listings before launch. See the note at the top of content.ts.
 *
 * `cbiEligible` is derived from the Türkiye Citizenship by Investment
 * property threshold (USD 400,000). Verify the current threshold before
 * relying on it commercially.
 */

export type Currency = "USD" | "EUR" | "TRY";

export type Unit = {
  slug: string;
  title: string;
  project: string;
  location: string;
  country: string;
  prices: Record<Currency, number>;
  type: string;
  bathrooms: string;
  bedroom: string;
  size: string;
  level: string;
  view: string;
  soldOut: boolean;
  cbiEligible: boolean;
  image: string;
};

export const currencies: Currency[] = ["USD", "EUR", "TRY"];

/** Türkiye CBI real-estate threshold, in USD. */
export const CBI_THRESHOLD_USD = 400000;

export const propertyTypes = ["Apartment", "Townhouse", "Villa"];

export const bedroomOptions = ["Studio", "1", "2", "3", "5"];

export const locations = [
  "Türkiye",
  "Caribbean",
  "İstanbul",
  "Antalya",
  "Muğla",
  "Grenada",
];

export const priceCeilings: Record<Currency, number[]> = {
  USD: [200000, 400000, 600000, 800000, 1000000, 1500000, 2000000],
  EUR: [180000, 360000, 550000, 730000, 920000, 1380000, 1840000],
  TRY: [8000000, 16000000, 24000000, 32000000, 40000000, 60000000, 80000000],
};

export const units: Unit[] = [
  {
    slug: "the-la-sagesse-collection-residences-studio",
    title: "The La Sagesse Collection Residences Studio",
    project: "The La Sagesse Collection Residences",
    location: "Grenada",
    country: "Caribbean",
    prices: { USD: 350000, EUR: 322000, TRY: 14400000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "Studio",
    size: "398.26 sq. ft.",
    level: "Level 1-3",
    view: "Sea View & Island View",
    soldOut: false,
    cbiEligible: false,
    image: "/images/units/master-bedroom-1-1.webp",
  },
  {
    slug: "the-la-sagesse-collection-residences-2-bedroom",
    title: "The La Sagesse Collection Residences 2 Bedroom",
    project: "The La Sagesse Collection Residences",
    location: "Grenada",
    country: "Caribbean",
    prices: { USD: 735000, EUR: 676000, TRY: 30100000 },
    type: "Apartment",
    bathrooms: "2 Bathroom",
    bedroom: "2 Bedroom",
    size: "1,544.61 sq. ft.",
    level: "Level 1-3",
    view: "Sea View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/master-bedroom-1-1.webp",
  },
  {
    slug: "marmara-vista-2-bedroom",
    title: "Marmara Vista 2 Bedroom",
    project: "Marmara Vista",
    location: "Beylikd\u00fcz\u00fc",
    country: "T\u00fcrkiye",
    prices: { USD: 1230000, EUR: 1132000, TRY: 50400000 },
    type: "Apartment",
    bathrooms: "2 Bathroom",
    bedroom: "2 Bedroom",
    size: "1,297.59 sq. ft.",
    level: "First Floor",
    view: "City View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/2bedroom-overlookingwynn01-wynngold-02-1-2.webp",
  },
  {
    slug: "marmara-vista-1-bedroom",
    title: "Marmara Vista 1 Bedroom",
    project: "Marmara Vista",
    location: "Beylikd\u00fcz\u00fc",
    country: "T\u00fcrkiye",
    prices: { USD: 540000, EUR: 497000, TRY: 22100000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "1 Bedroom",
    size: "1,709.20 sq. ft.",
    level: "Ground Floor",
    view: "City View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/1bedroomupdate-1.webp",
  },
  {
    slug: "marmara-vista-2-bedroom-2",
    title: "Marmara Vista 2 Bedroom",
    project: "Marmara Vista",
    location: "Beylikd\u00fcz\u00fc",
    country: "T\u00fcrkiye",
    prices: { USD: 1230000, EUR: 1132000, TRY: 50400000 },
    type: "Apartment",
    bathrooms: "2 Bathroom",
    bedroom: "2 Bedroom",
    size: "1,709.20 sq. ft.",
    level: "Ground Floor",
    view: "City View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/2bedroom-overlookingwynn01-wynngold-02-1-2.webp",
  },
  {
    slug: "bosphorus-heights-1-bedroom",
    title: "Bosphorus Heights 1 Bedroom",
    project: "Bosphorus Heights",
    location: "Beyo\u011flu",
    country: "T\u00fcrkiye",
    prices: { USD: 455000, EUR: 419000, TRY: 18700000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "1 Bedroom",
    size: "768.95 - 951.42 sq. ft.",
    level: "Level 2",
    view: "City View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/67ce59d2dd9f38b5ba355f6b-5486-al-marjan-bath.webp",
  },
  {
    slug: "bosphorus-heights-studio",
    title: "Bosphorus Heights Studio",
    project: "Bosphorus Heights",
    location: "Beyo\u011flu",
    country: "T\u00fcrkiye",
    prices: { USD: 270000, EUR: 248000, TRY: 11100000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "Studio",
    size: "480.93 - 511.18 sq. ft.",
    level: "Level 2",
    view: "City View",
    soldOut: false,
    cbiEligible: false,
    image: "/images/units/5486-al-marjan-bedroom-01.webp",
  },
  {
    slug: "bosphorus-heights-1-bedroom-2",
    title: "Bosphorus Heights 1 Bedroom",
    project: "Bosphorus Heights",
    location: "Beyo\u011flu",
    country: "T\u00fcrkiye",
    prices: { USD: 455000, EUR: 419000, TRY: 18700000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "1 Bedroom",
    size: "845.51 - 1,165.41 sq. ft.",
    level: "Level 1",
    view: "City View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/67ce59d2dd9f38b5ba355f6b-5486-al-marjan-bath.webp",
  },
  {
    slug: "bosphorus-heights-studio-2",
    title: "Bosphorus Heights Studio",
    project: "Bosphorus Heights",
    location: "Beyo\u011flu",
    country: "T\u00fcrkiye",
    prices: { USD: 270000, EUR: 248000, TRY: 11100000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "Studio",
    size: "866.39 - 935.81 sq. ft.",
    level: "Level 1",
    view: "City View",
    soldOut: false,
    cbiEligible: false,
    image: "/images/units/67ce59d2dd9f38b5ba355f6b-5486-al-marjan-bath.webp",
  },
  {
    slug: "aegean-bay-residences-3-bedroom-duplex",
    title: "Aegean Bay Residences 3 Bedroom Duplex",
    project: "Aegean Bay Residences",
    location: "Bodrum",
    country: "T\u00fcrkiye",
    prices: { USD: 1880000, EUR: 1730000, TRY: 77100000 },
    type: "Apartment",
    bathrooms: "4 Bathroom",
    bedroom: "3 Bedroom",
    size: "1,942.67 - 2,315.64 sq. ft.",
    level: "Sky Lofts",
    view: "Island & Casino",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/5486-al-marjan-bedroom-01.webp",
  },
  {
    slug: "aegean-bay-residences-2-bedroom-duplex",
    title: "Aegean Bay Residences 2 Bedroom Duplex",
    project: "Aegean Bay Residences",
    location: "Bodrum",
    country: "T\u00fcrkiye",
    prices: { USD: 1635000, EUR: 1504000, TRY: 67000000 },
    type: "Apartment",
    bathrooms: "3 Bathroom",
    bedroom: "2 Bedroom",
    size: "1,998.97 sq. ft.",
    level: "Sky Lofts",
    view: "Island & Casino",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/67ce59d2dd9f38b5ba355f6b-5486-al-marjan-bath.webp",
  },
  {
    slug: "aegean-bay-residences-1-bedroom-simplex",
    title: "Aegean Bay Residences 1 Bedroom Simplex",
    project: "Aegean Bay Residences",
    location: "Bodrum",
    country: "T\u00fcrkiye",
    prices: { USD: 570000, EUR: 524000, TRY: 23400000 },
    type: "Apartment",
    bathrooms: "2 Bathroom",
    bedroom: "1 Bedroom",
    size: "864.34 - 955.51 sq. ft.",
    level: "Sky Lofts",
    view: "Island & Casino",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/aimarj-1.webp",
  },
  {
    slug: "aegean-bay-residences-2-bedroom",
    title: "Aegean Bay Residences 2 Bedroom",
    project: "Aegean Bay Residences",
    location: "Bodrum",
    country: "T\u00fcrkiye",
    prices: { USD: 1035000, EUR: 952000, TRY: 42400000 },
    type: "Apartment",
    bathrooms: "3 Bathroom",
    bedroom: "2 Bedroom",
    size: "1,660.55 - 1,840.41 sq. ft.",
    level: "Luxury Residences",
    view: "Island & Casino",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/aimarj-3.webp",
  },
  {
    slug: "aegean-bay-residences-1-bedroom",
    title: "Aegean Bay Residences 1 Bedroom",
    project: "Aegean Bay Residences",
    location: "Bodrum",
    country: "T\u00fcrkiye",
    prices: { USD: 845000, EUR: 777000, TRY: 34600000 },
    type: "Apartment",
    bathrooms: "2 Bathroom",
    bedroom: "1 Bedroom",
    size: "988.88 - 1,488.00 sq. ft.",
    level: "Luxury Residences",
    view: "Island & Casino",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/5486-al-marjan-living-03.webp",
  },
  {
    slug: "aegean-bay-residences-studio",
    title: "Aegean Bay Residences Studio",
    project: "Aegean Bay Residences",
    location: "Bodrum",
    country: "T\u00fcrkiye",
    prices: { USD: 355000, EUR: 327000, TRY: 14600000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "Studio",
    size: "527.75 - 664.99 sq. ft.",
    level: "Luxury Residences",
    view: "Island & Casino",
    soldOut: false,
    cbiEligible: false,
    image: "/images/units/5486-al-marjan-bedroom-02.webp",
  },
  {
    slug: "levent-residences-1-bedroom",
    title: "Levent Residences 1 Bedroom",
    project: "Levent Residences",
    location: "\u015ei\u015fli",
    country: "T\u00fcrkiye",
    prices: { USD: 680000, EUR: 626000, TRY: 27900000 },
    type: "Apartment",
    bathrooms: "2 Bathroom",
    bedroom: "1 Bedroom",
    size: "1,501.93 - 2,203.30 sq. ft.",
    level: "East Wing",
    view: "Sea View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/rak-bedroom-pptp02-1-1-1.webp",
  },
  {
    slug: "levent-residences-studio",
    title: "Levent Residences Studio",
    project: "Levent Residences",
    location: "\u015ei\u015fli",
    country: "T\u00fcrkiye",
    prices: { USD: 380000, EUR: 350000, TRY: 15600000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "Studio",
    size: "635.56 - 1,866.13 sq. ft.",
    level: "East Wing",
    view: "Sea View",
    soldOut: false,
    cbiEligible: false,
    image: "/images/units/bedroom02-pptp02-2-1.webp",
  },
  {
    slug: "levent-residences-5-bedroom-townhouse-plus-maid",
    title: "Levent Residences 5 Bedroom Townhouse + Maid",
    project: "Levent Residences",
    location: "\u015ei\u015fli",
    country: "T\u00fcrkiye",
    prices: { USD: 165000, EUR: 152000, TRY: 6800000 },
    type: "Townhouse",
    bathrooms: "5 Bathroom",
    bedroom: "5 Bedroom",
    size: "6,525.84 sq. ft.",
    level: "Townhouses",
    view: "Sea View",
    soldOut: true,
    cbiEligible: false,
    image: "/images/units/townhouse-bedroom01-pptp02-1.webp",
  },
  {
    slug: "aegean-bay-residences-1-bedroom-simplex-2",
    title: "Aegean Bay Residences 1 Bedroom Simplex",
    project: "Aegean Bay Residences",
    location: "Bodrum",
    country: "T\u00fcrkiye",
    prices: { USD: 600000, EUR: 552000, TRY: 24600000 },
    type: "Apartment",
    bathrooms: "2 Bathroom",
    bedroom: "1 Bedroom",
    size: "866.39 - 935.81 sq. ft.",
    level: "Marjan Lofts",
    view: "Island & Casino",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/1-the-beach-house.webp",
  },
  {
    slug: "aegean-bay-residences-2-bedroom-duplex-2",
    title: "Aegean Bay Residences 2 Bedroom Duplex",
    project: "Aegean Bay Residences",
    location: "Bodrum",
    country: "T\u00fcrkiye",
    prices: { USD: 1415000, EUR: 1302000, TRY: 58000000 },
    type: "Apartment",
    bathrooms: "3 Bathroom",
    bedroom: "2 Bedroom",
    size: "2,007.90 sq. ft.",
    level: "Mrjan Lofts",
    view: "Island & Casino",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/5486-al-marjan-bathroom-05.webp",
  },
  {
    slug: "aegean-bay-residences-3-bedroom-duplex-2",
    title: "Aegean Bay Residences 3 Bedroom Duplex",
    project: "Aegean Bay Residences",
    location: "Bodrum",
    country: "T\u00fcrkiye",
    prices: { USD: 1525000, EUR: 1403000, TRY: 62500000 },
    type: "Apartment",
    bathrooms: "4 Bathroom",
    bedroom: "3 Bedroom",
    size: "1,841.27 - 2,029.32 sq. ft.",
    level: "Marjan Lofts",
    view: "Island & Casino",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/5486-al-marjan-bedroom-03.webp",
  },
  {
    slug: "levent-residences-studio-2",
    title: "Levent Residences Studio",
    project: "Levent Residences",
    location: "\u015ei\u015fli",
    country: "T\u00fcrkiye",
    prices: { USD: 355000, EUR: 327000, TRY: 14600000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "Studio",
    size: "583.46 - 6,86.51 sq. ft.",
    level: "West Wing",
    view: "Sea View",
    soldOut: false,
    cbiEligible: false,
    image: "/images/units/5486-al-marjan-living-02.webp",
  },
  {
    slug: "levent-residences-1-bedroom-2",
    title: "Levent Residences 1 Bedroom",
    project: "Levent Residences",
    location: "\u015ei\u015fli",
    country: "T\u00fcrkiye",
    prices: { USD: 625000, EUR: 575000, TRY: 25600000 },
    type: "Apartment",
    bathrooms: "2 Bathroom",
    bedroom: "1 Bedroom",
    size: "965.18 - 1,586.07 sq. ft.",
    level: "West Wing",
    view: "Sea View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/2-the-beach-residences-1.webp",
  },
  {
    slug: "levent-residences-2-bedroom",
    title: "Levent Residences 2 Bedroom",
    project: "Levent Residences",
    location: "\u015ei\u015fli",
    country: "T\u00fcrkiye",
    prices: { USD: 1225000, EUR: 1127000, TRY: 50200000 },
    type: "Apartment",
    bathrooms: "4 Bathroom",
    bedroom: "2 Bedroom",
    size: "2,147.43 - 2,958.41 sq. ft.",
    level: "West Wing",
    view: "Sea View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/6-1-2.webp",
  },
  {
    slug: "levent-residences-3-bedroom",
    title: "Levent Residences 3 Bedroom",
    project: "Levent Residences",
    location: "\u015ei\u015fli",
    country: "T\u00fcrkiye",
    prices: { USD: 1770000, EUR: 1628000, TRY: 72600000 },
    type: "Apartment",
    bathrooms: "4 Bathroom",
    bedroom: "3 Bedroom",
    size: "3,354.13 - 4,318.53 sq. ft.",
    level: "West Wing",
    view: "Sea View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/image-39.webp",
  },
  {
    slug: "levent-residences-3-bedroom-townhouse-plus-maid",
    title: "Levent Residences 3 Bedroom Townhouse + Maid",
    project: "Levent Residences",
    location: "\u015ei\u015fli",
    country: "T\u00fcrkiye",
    prices: { USD: 165000, EUR: 152000, TRY: 6800000 },
    type: "Townhouse",
    bathrooms: "4 Bathroom",
    bedroom: "3 Bedroom",
    size: "3,309.58 - 3,410.76 sq. ft.",
    level: "Townhouses",
    view: "Sea View",
    soldOut: true,
    cbiEligible: false,
    image: "/images/units/bedroom02-pptp02-1-12.webp",
  },
  {
    slug: "marmara-vista-studio",
    title: "Marmara Vista Studio",
    project: "Marmara Vista",
    location: "Beylikd\u00fcz\u00fc",
    country: "T\u00fcrkiye",
    prices: { USD: 310000, EUR: 285000, TRY: 12700000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "Studio",
    size: "479 - 533 sq. ft.",
    level: "Level 1-15",
    view: "City View",
    soldOut: false,
    cbiEligible: false,
    image: "/images/units/image-4.webp",
  },
  {
    slug: "marmara-vista-1-bedroom-2",
    title: "Marmara Vista 1 Bedroom",
    project: "Marmara Vista",
    location: "Beylikd\u00fcz\u00fc",
    country: "T\u00fcrkiye",
    prices: { USD: 405000, EUR: 373000, TRY: 16600000 },
    type: "Apartment",
    bathrooms: "1 Bathroom",
    bedroom: "1 Bedroom",
    size: "479 - 893 sq. ft.",
    level: "Level 1-15",
    view: "City View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/image-41.webp",
  },
  {
    slug: "marmara-vista-2-bedroom-3",
    title: "Marmara Vista 2 Bedroom",
    project: "Marmara Vista",
    location: "Beylikd\u00fcz\u00fc",
    country: "T\u00fcrkiye",
    prices: { USD: 1230000, EUR: 1132000, TRY: 50400000 },
    type: "Apartment",
    bathrooms: "2 Bathroom",
    bedroom: "2 Bedroom",
    size: "1,589 - 1,709 sq. ft.",
    level: "Level 1-15",
    view: "Casino & Island View",
    soldOut: false,
    cbiEligible: true,
    image: "/images/units/image-40.webp",
  },
];
